[tool.poetry]
name = "module3-course-work"
version = "0.1.0"
description = ""
authors = ["rafaelmanasyan <workpageraf@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
